
# require: rubocop-rspec

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - ext/**/Rakefile
    - lib/**/*.{rb,rake}
    - spec/**/*.rb

  NewCops: enable
  TargetRubyVersion: 2.3

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case
