require 'ffi-compiler/compile_task'

FFI::Compiler::CompileTask.new('scrypt_ext') do |t|
  t.cflags << "-Wall -msse -msse2"
  t.cflags << "-D_GNU_SOURCE=1" if RbConfig::CONFIG["host_os"].downcase =~ /mingw/
  t.cflags << "-arch x86_64 -arch i386" if t.platform.mac?
  t.ldflags << "-arch x86_64 -arch i386" if t.platform.mac?
  t.export '../../lib/scrypt/scrypt_ext.rb'
end
